status = [
  "ci/circleci: update_track",
  "ci/circleci: install_and_buildx",
  "ci/circleci: test",
  # "ci/circleci: run-e2e-tests",
  "ci/circleci: run-smoke-tests",
  "ci/circleci: provision-env",
  "ci/circleci: prepare-env",
]
delete_merged_branches = true
use_squash_merge = true
cut_body_after = "### Implementation details. How do you make this change?"
required_approvals=1
update_base_for_deletes = true
