version: 2.1
setup: true

parameters:
  ssh-fingerprint:
    type: string
    default: "SHA256:7FhWIIg1mYzFjcATPWZB3H9VVpUQihp2rQh1HFhPdks"

orbs:
  vfcommon: voiceflow/common@0.60.0
  gomplate: xavientois/gomplate@0.2.0

workflows:
  generate-config:
    when:
      and:
        - << pipeline.git.branch >> # Run nothing on tags
        - not:
            equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - gomplate/render-config:
          context: dev-test
          executor: vfcommon/node-executor
          pre-steps:
            - checkout
            - vfcommon/set-env-name: # On bors branches, we will be running the e2e tests in a dev environment
                target_env_var: &env_name ENV_NAME
            - vfcommon/set-json-string-from-env:
                field: e2e_env_name
                value-env-var: *env_name
            - vfcommon/set-json-string:
                field: branch
                # HACK: this cannot be empty, so we pass both branch and tag (only one of them will be non-empty)
                # TODO: Fix this once https://discuss.circleci.com/t/empty-string-for-parameter-breaks-config/47695 has a solution
                value: "<< pipeline.git.branch >><< pipeline.git.tag >>"
            - vfcommon/set-json-command:
                field: node_version
                command: jq --raw-output '.volta.node // ""' package.json | sed -E "s/^([0-9]+)(\.[0-9]+)?.*$/\1\2/g"
            - vfcommon/set-json-string:
                field: common_orb_version
                value: "0.60.0"
            - run: cat values.json
          contexts: values.json


  # Cron Production update
  update-production-branch:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "update-production-branch", << pipeline.schedule.name >> ]
    jobs:
      - vfcommon/sync_branches:
          checkout: true
          ssh_key: << pipeline.parameters.ssh-fingerprint >>
          name: sync-branches-scheduled
          context: dev-test
          filters:
            branches:
              only: master
