name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: MASTER
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@main
        env:
          DAY_OF_WEEK: MASTER
        with:
          rdme: openapi backend/docs/openapi.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }}
